// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdLPLsZ8M6IX4VrGPAifqtWNakJkUP4Og',
    appId: '1:727964086455:android:f14621a65a58fadf089d32',
    messagingSenderId: '727964086455',
    projectId: 'iot-project-610d9',
    databaseURL: 'https://iot-project-610d9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-610d9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQRgQzKFdFxFDMz9OLzfPf1tDzVK0uoo',
    appId: '1:727964086455:web:892256c1ef75452d089d32',
    messagingSenderId: '727964086455',
    projectId: 'iot-project-610d9',
    authDomain: 'iot-project-610d9.firebaseapp.com',
    databaseURL: 'https://iot-project-610d9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-610d9.firebasestorage.app',
    measurementId: 'G-Z0H64JRMQS',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQRgQzKFdFxFDMz9OLzfPf1tDzVK0uoo',
    appId: '1:727964086455:web:892256c1ef75452d089d32',
    messagingSenderId: '727964086455',
    projectId: 'iot-project-610d9',
    authDomain: 'iot-project-610d9.firebaseapp.com',
    databaseURL: 'https://iot-project-610d9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-610d9.firebasestorage.app',
    measurementId: 'G-Z0H64JRMQS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYxelLL5oz1nhGEl6yVViqoyUbvmPpeU',
    appId: '1:246425953267:ios:818b36a9ad474986772886',
    messagingSenderId: '246425953267',
    projectId: 'hi-firebase-58871',
    storageBucket: 'hi-firebase-58871.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYxelLL5oz1nhGEl6yVViqoyUbvmPpeU',
    appId: '1:246425953267:ios:818b36a9ad474986772886',
    messagingSenderId: '246425953267',
    projectId: 'hi-firebase-58871',
    storageBucket: 'hi-firebase-58871.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

}